version: '3'

services:
  db:
    build: .
#    image: postgres:14.0
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
    user: "root"
volumes:
  db-store: